spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

spring.application.name=cine-java
server.servlet.context-path=/cine-java/api

#PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

#LangChain4j
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
