server.port=8090

#Spring Data JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/cine_java_db
spring.datasource.username=facundo
spring.datasource.password=facundo.java

#LangChain4j
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.embedding-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
logging.level.dev.langcain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG
