package com.cine_java.domain.dto;

import com.cine_java.domain.Genre;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.*;

import java.time.LocalDate;

public record MovieDto(

        @Schema(
                description = "Unique ID generated by the database",
                example = "9",
                accessMode = Schema.AccessMode.READ_ONLY
        )
        Long id,


        @Schema(
                description = "Movie title",
                example = "Joker"
        )
        @NotBlank(message = "La pelicula debe tener un titulo que no esté vacío")
        String title,


        @Schema(
                description = "Movie runtime in minutes",
                example = "194"
        )
        @Positive(message = "El valor de la duración debe ser un número positivo")
        Integer duration,


        @Schema(
                description = "Movie genre",
                example = "DRAMA"
        )
        Genre genre,


        @Schema(
                description = "Movie release date"
        )
        @PastOrPresent(message = "La fecha de lanzamiento debe ser anterior o igual a la actual")
        LocalDate releaseDate,

        @Schema(
                description = "Movie rating",
                example = "8.6",
                minimum = "0",
                maximum = "10"
        )
        @Min(value = 0, message = "El valor mínimo de calificación debe ser cero")
        @Max(value = 10, message = "El valor máximo de la calificación debe ser diez")
        Double rating,


        @Schema(
                description = "Indicates whether the movie is available. true represents available.",
                example = "true",
                accessMode =  Schema.AccessMode.READ_ONLY
        )
        Boolean state
) {
}
